// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW-2JY-k34l85nrnRoJTozav3A-i1zizQ',
    appId: '1:49819555020:web:9cf1d505d1dc4e03649e69',
    messagingSenderId: '49819555020',
    projectId: 'skype-bec7e',
    authDomain: 'skype-bec7e.firebaseapp.com',
    storageBucket: 'skype-bec7e.appspot.com',
    measurementId: 'G-PXJRT37SX7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTn57q4gj_9iwCnQYN3xDWCEETZCgEB5o',
    appId: '1:49819555020:android:75ab54bd2d69973c649e69',
    messagingSenderId: '49819555020',
    projectId: 'skype-bec7e',
    storageBucket: 'skype-bec7e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKbRAom9VAbsnDuKRy3ndyq55sci-ih9A',
    appId: '1:49819555020:ios:f5e6b973bd1c031d649e69',
    messagingSenderId: '49819555020',
    projectId: 'skype-bec7e',
    storageBucket: 'skype-bec7e.appspot.com',
    iosBundleId: 'com.example.skypeApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKbRAom9VAbsnDuKRy3ndyq55sci-ih9A',
    appId: '1:49819555020:ios:05b11fb2050ef52a649e69',
    messagingSenderId: '49819555020',
    projectId: 'skype-bec7e',
    storageBucket: 'skype-bec7e.appspot.com',
    iosBundleId: 'com.example.skypeApplication.RunnerTests',
  );
}
